# This file has been generated by node2nix 1.9.0. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {};
in {
  pnpm = nodeEnv.buildNodePackage {
    name = "pnpm";
    packageName = "pnpm";
    version = "7.0.0-rc.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-7.0.0-rc.9.tgz";
      sha256 = "sha256-PinLfpnDvNXNnecbdJO+ioghLtB1m29KAqZ+AJ6afLE=";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, disk space efficient package manager";
      homepage = "https://pnpm.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
